version: "3.7"

services:
  postgres:
    image: postgres:16.2-alpine3.19
    container_name: fsw-foods
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=fsw
      - POSTGRES_PASSWORD=admfsw
      - POSTGRES_DB=fswfoods
    volumes:
      - "db:/var/lib/postgresql/data"
    networks:
      - amize

networks:
  amize:
    driver: bridge

volumes:
  db:
